# Site settings
title: Juncheng's Blog
url: "http://jli98.github.io"
baseurl:
#timezone: Asia/Chongqing
description: 这就是我写点东西的地方啦。

# Your information
email: smell_smelly@163.com
author: Juncheng Li
avatar: "/images/avatar.jpeg"
profile: 
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
